version: '3'

volumes:
  pg_data2:
  static:
  mediafiles:

services:
  foodgram:
    image: postgres:13.10
    env_file: .env.example
    volumes:
      - pg_data2:/var/lib/postgresql/data
  backend:
    build: ./backend_foodgram/
    env_file: .env.example
    volumes:
      - static:/backend_foodgram_static
      - mediafiles:/backend_foodgram_media
    depends_on:
      - foodgram
  frontend:
    env_file: .env.example
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./nginx/
    volumes:
      - static:/staticfiles/
      - mediafiles:/media/
    depends_on:
      - frontend
      - backend
    ports:
      - 9999:80 
